defaults:
    - _self_
    - base_separation
    - override /dataset: test_mnist
    - override /vqvae: mnist_256
    - override /autoregressive: mnist_256
    - override /separation_method: general

checkpoints:
    vqvae: lass_mnist/checkpoints/vqvae/256-sigmoid-big.pt
    autoregressive: lass_mnist/checkpoints/unconditioned/256-sigmoid-big.pt
    sums: lass_mnist/checkpoints/sum/256-sigmoid-big.pt

batch_size: 64
latent_length: 7
vocab_size: 256
